#!/bin/bash

sleep 10

cd /sys/kernel/config/usb_gadget/
mkdir -p g_rpi_hid_keyboard
cd g_rpi_hid_keyboard

# Define USB specification
echo 0x1d6b > idVendor # Linux Foundation
echo 0x0104 > idProduct # Multifunction Composite Joystick Gadget
echo 0x0100 > bcdDevice # v1.0.0
echo 0x0200 > bcdUSB # USB2
echo 0x00 > bDeviceClass
echo 0x00 > bDeviceSubClass
echo 0x00 > bDeviceProtocol

mkdir -p strings/0x409
echo "6633663366" > strings/0x409/serialnumber
echo "Raspberry Pi" > strings/0x409/manufacturer
echo "RaspberryPi Virtual keyboard" > strings/0x409/product

# Define the functions of the device
mkdir -p functions/hid.usb0
echo 0 > functions/hid.usb0/subclass
echo 1 > functions/hid.usb0/protocol
echo 8 > functions/hid.usb0/report_length
# echo 63 > functions/hid.usb0/report_desc_length

# Write report descriptor from report_desc attribut in hidg_func_descriptor struct
echo "05010906A101050719e029e71500250175019508810295017508810395057501050819012905910295017503910395067508150025650507190029658100C0" | xxd -r -ps > functions/hid.usb0/report_desc

# Create configuration file
mkdir -p configs/c.1/strings/0x409

echo 0x80 > configs/c.1/bmAttributes
echo 100 > configs/c.1/MaxPower # 100 mA
echo "RaspberryPi Virtual keyboard Configuration" > configs/c.1/strings/0x409/configuration

# Link the configuration file
ln -s functions/hid.usb0 configs/c.1

# Activate device
ls /sys/class/udc > UDC

sleep 10